// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transactions.Data;

namespace Transactions.Migrations
{
    [DbContext(typeof(AppDBContent))]
    partial class AppDBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transactions.Data.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("customer_id");

                    b.Property<int>("gender");

                    b.HasKey("id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Transactions.Data.Models.MccCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("mcc_code");

                    b.Property<string>("mcc_description");

                    b.HasKey("id");

                    b.ToTable("MccCode");
                });

            modelBuilder.Entity("Transactions.Data.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("amount");

                    b.Property<int>("customer_id");

                    b.Property<int>("mcc_code");

                    b.Property<string>("term_id");

                    b.Property<string>("tr_datetime");

                    b.Property<int>("tr_type");

                    b.HasKey("id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Transactions.Data.Models.TransactionsType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tr_description");

                    b.Property<int>("tr_type");

                    b.HasKey("id");

                    b.ToTable("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
